language: csharp
mono: none
dotnet: 2.1.302
dist: trusty
install:
  - dotnet restore
script:
  - dotnet build -c Release InstallUtil.sln
  - dotnet pack -c Release
deploy:
  skip_cleanup: true
  provider: script
  script: dotnet nuget push ./InstallUtil/bin/Release/InstallUtil*.nupkg -k $NUGET_API_KEY -s $NUGET_SOURCE
  on:
    tags: true
    all_branches: true
